#!/bin/bash

# Vanguard Admin Creation Helper Script
# This script provides step-by-step instructions to create an admin user

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         VANGUARD ADMIN USER CREATION GUIDE                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Follow these steps to create your first admin user:"
echo ""
echo "📋 STEP 1: Create User in Firebase Authentication"
echo "   1. Open: https://console.firebase.google.com/project/portfolio-5ee70/authentication/users"
echo "   2. Click 'Add User'"
echo "   3. Enter email: admin@vanguard.com (or your preferred email)"
echo "   4. Enter a strong password (min 8 characters)"
echo "   5. Click 'Add User'"
echo "   6. COPY THE USER UID (you'll need this in Step 2)"
echo ""
read -p "Press Enter when you've completed Step 1 and copied the User UID..."
echo ""
echo "📝 STEP 2: Create Admin Document in Firestore"
echo "   1. Open: https://console.firebase.google.com/project/portfolio-5ee70/firestore/databases/vanguard-db/data"
echo "   2. Click 'Start collection'"
echo "   3. Collection ID: users"
echo "   4. Document ID: [PASTE THE USER UID FROM STEP 1]"
echo "   5. Add the following fields:"
echo ""
echo "   Field Name          | Type      | Value"
echo "   -------------------|-----------|----------------------------------"
echo "   id                 | string    | [SAME USER UID]"
echo "   name               | string    | Admin User"
echo "   email              | string    | admin@vanguard.com"
echo "   role               | string    | admin"
echo "   status             | string    | active"
echo "   department         | string    | Management"
echo "   phone              | string    | +1234567890"
echo "   avatar             | string    | (leave empty)"
echo "   createdAt          | timestamp | (click 'Set to current time')"
echo ""
echo "   6. Click 'Save'"
echo ""
read -p "Press Enter when you've completed Step 2..."
echo ""
echo "✅ STEP 3: Verify Admin Access"
echo "   1. Open: https://vanguard-management.web.app"
echo "   2. Login with your admin credentials"
echo "   3. You should see the full admin dashboard"
echo ""
echo "🎉 Admin user creation complete!"
echo ""
echo "📚 For more details, see ADMIN_SETUP.md"
echo ""
